# Generated by Django 5.1.7 on 2025-04-01 05:22

import django.db.models.deletion
import django.utils.timezone
import real_estate_dashapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'city_dim',
            },
        ),
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=real_estate_dashapp.models.upload_csv_path)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DimCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_market', models.CharField(blank=True, max_length=255, null=True)),
                ('is_furnished', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_construction', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_characteristic',
            },
        ),
        migrations.CreateModel(
            name='DimNumeric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField(blank=True, null=True)),
                ('number_of_rooms', models.FloatField(blank=True, null=True)),
                ('floors', models.FloatField(blank=True, null=True)),
                ('total_floors', models.FloatField(blank=True, null=True)),
                ('price_per_sqm', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_numeric',
            },
        ),
        migrations.CreateModel(
            name='DimTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dim_time',
            },
        ),
        migrations.CreateModel(
            name='DistrictDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'district_dim',
            },
        ),
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('extracted_data', models.JSONField(default=dict)),
                ('loaded_data', models.JSONField(default=dict)),
                ('total_extracted', models.IntegerField(default=0)),
                ('total_loaded', models.IntegerField(default=0)),
                ('status', models.CharField(default='Start', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRateDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(unique=True)),
                ('usd_uzs_rate', models.FloatField()),
            ],
            options={
                'db_table': 'exchange_rate_dim',
            },
        ),
        migrations.CreateModel(
            name='FoundationDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'foundation_dim',
            },
        ),
        migrations.CreateModel(
            name='LatLonDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lat_lon_dim',
            },
        ),
        migrations.CreateModel(
            name='LayoutDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'layout_dim',
            },
        ),
        migrations.CreateModel(
            name='RegionDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'region_dim',
            },
        ),
        migrations.CreateModel(
            name='RepairDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'repair_dim',
            },
        ),
        migrations.CreateModel(
            name='WCDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'wc_dim',
            },
        ),
        migrations.CreateModel(
            name='DimLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.citydim')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.districtdim')),
                ('lat_lon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.latlondim')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.regiondim')),
            ],
            options={
                'db_table': 'dim_location',
            },
        ),
        migrations.CreateModel(
            name='FactApartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('characteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.dimcharacteristic')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.dimlocation')),
                ('numeric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.dimnumeric')),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.dimtime')),
            ],
            options={
                'db_table': 'fact_apartments',
            },
        ),
        migrations.AddField(
            model_name='dimcharacteristic',
            name='foundation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.foundationdim'),
        ),
        migrations.AddField(
            model_name='dimcharacteristic',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.layoutdim'),
        ),
        migrations.AddField(
            model_name='dimcharacteristic',
            name='repair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.repairdim'),
        ),
        migrations.AddField(
            model_name='dimcharacteristic',
            name='wc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate_dashapp.wcdim'),
        ),
    ]
