# Generated by Django 5.1.7 on 2025-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_dashapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dimcharacteristic',
            index=models.Index(fields=['layout'], name='dim_charact_layout__a9584b_idx'),
        ),
        migrations.AddIndex(
            model_name='dimcharacteristic',
            index=models.Index(fields=['foundation'], name='dim_charact_foundat_83233f_idx'),
        ),
        migrations.AddIndex(
            model_name='dimcharacteristic',
            index=models.Index(fields=['wc'], name='dim_charact_wc_id_e5bd59_idx'),
        ),
        migrations.AddIndex(
            model_name='dimcharacteristic',
            index=models.Index(fields=['repair'], name='dim_charact_repair__8f928f_idx'),
        ),
        migrations.AddIndex(
            model_name='dimlocation',
            index=models.Index(fields=['city'], name='dim_locatio_city_id_51ad9b_idx'),
        ),
        migrations.AddIndex(
            model_name='dimlocation',
            index=models.Index(fields=['region'], name='dim_locatio_region__056f15_idx'),
        ),
        migrations.AddIndex(
            model_name='dimlocation',
            index=models.Index(fields=['district'], name='dim_locatio_distric_bb2e83_idx'),
        ),
        migrations.AddIndex(
            model_name='dimlocation',
            index=models.Index(fields=['lat_lon'], name='dim_locatio_lat_lon_301a03_idx'),
        ),
        migrations.AddIndex(
            model_name='dimtime',
            index=models.Index(fields=['datetime'], name='dim_time_datetim_a07180_idx'),
        ),
        migrations.AddIndex(
            model_name='factapartments',
            index=models.Index(fields=['time'], name='fact_apartm_time_id_40a4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='factapartments',
            index=models.Index(fields=['location'], name='fact_apartm_locatio_27061b_idx'),
        ),
        migrations.AddIndex(
            model_name='factapartments',
            index=models.Index(fields=['numeric'], name='fact_apartm_numeric_680a64_idx'),
        ),
        migrations.AddIndex(
            model_name='factapartments',
            index=models.Index(fields=['characteristic'], name='fact_apartm_charact_a00471_idx'),
        ),
    ]
