# Generated by Django 5.1.7 on 2025-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_dashapp', '0002_dimcharacteristic_dim_charact_layout__a9584b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dimnumeric',
            index=models.Index(fields=['number_of_rooms'], name='dim_numeric_number__775706_idx'),
        ),
        migrations.AddIndex(
            model_name='dimnumeric',
            index=models.Index(fields=['total_floors'], name='dim_numeric_total_f_280806_idx'),
        ),
        migrations.AddIndex(
            model_name='dimnumeric',
            index=models.Index(fields=['floors'], name='dim_numeric_floors_271b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='districtdim',
            index=models.Index(fields=['district_name'], name='district_di_distric_515f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='regiondim',
            index=models.Index(fields=['region_name'], name='region_dim_region__4f9445_idx'),
        ),
    ]
