# Generated by Django 5.1.7 on 2025-04-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_dashapp', '0003_dimnumeric_dim_numeric_number__775706_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dimcharacteristic',
            name='dim_charact_layout__a9584b_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimcharacteristic',
            name='dim_charact_foundat_83233f_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimcharacteristic',
            name='dim_charact_wc_id_e5bd59_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimcharacteristic',
            name='dim_charact_repair__8f928f_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimlocation',
            name='dim_locatio_city_id_51ad9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimlocation',
            name='dim_locatio_region__056f15_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimlocation',
            name='dim_locatio_distric_bb2e83_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimlocation',
            name='dim_locatio_lat_lon_301a03_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimnumeric',
            name='dim_numeric_number__775706_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimnumeric',
            name='dim_numeric_total_f_280806_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimnumeric',
            name='dim_numeric_floors_271b4d_idx',
        ),
        migrations.RemoveIndex(
            model_name='dimtime',
            name='dim_time_datetim_a07180_idx',
        ),
        migrations.RemoveIndex(
            model_name='districtdim',
            name='district_di_distric_515f7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='factapartments',
            name='fact_apartm_time_id_40a4c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='factapartments',
            name='fact_apartm_locatio_27061b_idx',
        ),
        migrations.RemoveIndex(
            model_name='factapartments',
            name='fact_apartm_numeric_680a64_idx',
        ),
        migrations.RemoveIndex(
            model_name='factapartments',
            name='fact_apartm_charact_a00471_idx',
        ),
        migrations.RemoveIndex(
            model_name='regiondim',
            name='region_dim_region__4f9445_idx',
        ),
    ]
